services:
  php:
    build:
      context: ./docker/php
    ports:
      - "8080:80"
    volumes:
      - ./site:/var/www/html

  scss:
    build:
      context: ./docker/scss
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: >
      sh -c "sass --watch --no-source-map src/scss:site/css --style compressed"

  watcher:
    build:
      context: ./docker/watcher
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: >
      sh -c "while inotifywait -r -e modify,create,delete /app/src/markdown /app/src/html; do
               sh scripts/convert.sh;
             done"
